import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { useEffect } from "react";
import CreateTodo from "../components/CreateTodo";
import Todos from "../components/Todos";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [isDarkMode, setIsDarkMode] = useState(false);

  const toggleDarkMode = () => {
    const root = document.documentElement;
    if (isDarkMode) {
      root.classList.remove("dark");
    } else {
      root.classList.add("dark");
    }
    localStorage.setItem("theme", isDarkMode ? "light" : "dark");
    setIsDarkMode(!isDarkMode);
  };

  useEffect(() => {
    const root = document.documentElement;
    const theme = localStorage.getItem("theme");
    if (theme === "dark") {
      root.classList.add(theme);
      setIsDarkMode(true);
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col w-full h-screen bg-veryLightGray dark:bg-veryDarkBlue ">
        <div className="h-[30%] relative w-full">
          <Image
            src={`${
              isDarkMode ? "/bg-desktop-dark.jpg" : "/bg-desktop-light.jpg"
            }`}
            layout="fill"
            alt=""
            className="object-cover "
          />
        </div>
        <div className="absolute top-[7%] max-w-xl md:left-[50%] md:translate-x-[-50%]  px-5 flex flex-col w-full ">
          <div className="flex flex-row justify-between items-center w-full text-white">
            <h2 className="text-3xl md:text-4xl tracking-[0.7rem] font-bold">
              TODO
            </h2>
            <button onClick={toggleDarkMode} className="h-5 w-5 md:h-6 md:w-6">
              <Image
                src={`${isDarkMode ? "/icon-sun.svg" : "/icon-moon.svg"}`}
                height={30}
                width={30}
                alt="darkModeToggler"
                layout="responsive"
              />
            </button>
          </div>
          <CreateTodo />
          <Todos />
        </div>
      </div>
    </div>
  );
}
