import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useDispatch } from "react-redux";
import CreateTodo from "../components/CreateTodo";
import LoadingSpinner from "../components/LoadingSpinner";
import Todos from "../components/Todos";
import { auth } from "../store/authSlice";
import isAuthenticated from "../utils/isAuthenticated";

export default function Home() {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const dispatch = useDispatch();
  useEffect(() => {
    setLoading(true);
    if (!isAuthenticated()) {
      router.push("/register");
    } else {
      setLoading(false);
      const user = JSON.parse(localStorage.getItem("user"));
      dispatch(auth(user));
    }
  }, [router, dispatch]);

  if (loading) {
    return (
      <div className=" h-full mt-[18rem]  flex items-center justify-center">
        <div className="h-10 w-10 md:h-16 md:w-16 ">
          <LoadingSpinner />
        </div>
      </div>
    );
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {}
      <CreateTodo />
      <Todos />
    </div>
  );
}
